const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getTranslations: () => ipcRenderer.invoke('get-translations'),
  getLocale: () => ipcRenderer.invoke('get-locale'),
  setLocale: (lang) => ipcRenderer.invoke('set-locale', lang),
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
  loginMicrosoft: () => ipcRenderer.invoke('login-microsoft'),
  addOfflineAccount: (name) => ipcRenderer.invoke('add-offline-account', name),
  getAccounts: () => ipcRenderer.invoke('get-accounts'),
  setActiveAccount: (id) => ipcRenderer.invoke('set-active-account', id),
  removeAccount: (id) => ipcRenderer.invoke('remove-account', id),
  getSession: () => ipcRenderer.invoke('get-session'),
  launchGame: (profile) => ipcRenderer.invoke('launch-game', profile),
  openGameFolder: () => ipcRenderer.invoke('open-game-folder'),
  onWindowStateChange: (callback) => ipcRenderer.on('window-state', (event, isMaximized) => callback(isMaximized)),
  isMaximized: () => ipcRenderer.invoke('is-maximized'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  pickJava: () => ipcRenderer.invoke('pick-java'),
  getSystemRam: () => ipcRenderer.invoke('get-system-ram'),
  getVersions: () => ipcRenderer.invoke('get-versions'),
  getLoaderVersions: (loader, mcVersion) => ipcRenderer.invoke('get-loader-versions', loader, mcVersion),
  getAvailableLoaders: (mcVersion) => ipcRenderer.invoke('get-available-loaders', mcVersion),
  getJavaStatus: (mcVersion) => ipcRenderer.invoke('get-java-status', mcVersion),
  getJarMods: () => ipcRenderer.invoke('get-jarmods'),
  openJarModsFolder: () => ipcRenderer.invoke('open-jarmods-folder'),
  getInstances: () => ipcRenderer.invoke('get-instances'),
  createInstance: (draft) => ipcRenderer.invoke('create-instance', draft),
  selectInstance: (id) => ipcRenderer.invoke('select-instance', id),
  deleteInstance: (id) => ipcRenderer.invoke('delete-instance', id),
  openInstanceFolder: (id) => ipcRenderer.invoke('open-instance-folder', id),
  listInstanceMods: (id, kind) => ipcRenderer.invoke('list-instance-mods', id, kind),
  removeInstanceMod: (id, filename, kind) => ipcRenderer.invoke('remove-instance-mod', id, filename, kind),
  getModCategories: () => ipcRenderer.invoke('get-mod-categories'),
  getShaderSupport: (id) => ipcRenderer.invoke('get-shader-support', id),
  searchModpacks: (query, offset, categories) => ipcRenderer.invoke('search-modpacks', query, offset, categories),
  installModpack: (projectId) => ipcRenderer.invoke('install-modpack', projectId),
  pickModpackFile: () => ipcRenderer.invoke('pick-modpack-file'),
  installLocalModpack: (filePath) => ipcRenderer.invoke('install-local-modpack', filePath),
  onModpackProgress: (callback) => ipcRenderer.on('modpack-progress', (event, progress) => callback(progress)),
  onLaunchProgress: (callback) => ipcRenderer.on('launch-progress', (event, progress) => callback(progress)),
  searchMods: (id, query, offset, categories, kind) => ipcRenderer.invoke('search-mods', id, query, offset, categories, kind),
  installMod: (id, source, projectId, kind) => ipcRenderer.invoke('install-mod', id, source, projectId, kind),
  openCrashReports: () => ipcRenderer.invoke('open-crash-reports'),
  listCrashReports: () => ipcRenderer.invoke('list-crash-reports'),
  readCrashReport: (id) => ipcRenderer.invoke('read-crash-report', id),
  revealCrashReport: (id) => ipcRenderer.invoke('reveal-crash-report', id)
});
